name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest tabulate graphviz

      - name: Run placeholder test
        run: |
          echo "No tests yet. Skipping test step for now."

  smoke_export:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install graphviz

      - name: Make scripts executable
        run: |
          chmod +x export_pipeline.sh smoke_test_export_pipeline.sh

      - name: Run export smoke test
        run: bash smoke_test_export_pipeline.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: export-artifacts
          path: |
            echo_full_network.dot
            echo_full_network.png
            checkpoint_bridge.json
            checkpoint_bus.json
            export_manifest.json
            echo.whisperbus.archive
            export_pipeline.log
