name: Export & Smoke Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke_export:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install graphviz

      - name: Make shell scripts executable
        run: chmod +x export_pipeline.sh smoke_test_export_pipeline.sh

      - name: Run smoke test pipeline
        run: bash smoke_test_export_pipeline.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: export-artifacts
          path: |
            echo_full_network.dot
            echo_full_network.png
            checkpoint_bridge.json
            checkpoint_bus.json
            export_manifest.json
            echo.whisperbus.archive
            export_pipeline.log
          if-no-files-found: warn
