name: Export and Smoke Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  smoke_export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx pydot
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Make export script executable
        run: chmod +x export_pipeline.sh

      - name: Run export pipeline
        run: ./export_pipeline.sh

      - name: Upload export artifacts
        uses: actions/upload-artifact@v4
        with:
          name: export-artifacts
          path: |
            echo_full_network.dot
            echo_full_network.png
            checkpoint_bridge.json
            checkpoint_bus.json
            export_manifest.json
            echo.whisperbus.archive
            export_pipeline.log
