name: Export Pipeline and Artifact Check

on:
  push:
    branches: [main]

jobs:
  export_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz python3 python3-pip
          pip3 install networkx pydot

      - name: Run export pipeline
        run: ./export_pipeline.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: export-artifacts
          path: |
            echo_full_network.dot
            echo_full_network.png
            checkpoint_bridge.json
            checkpoint_bus.json
            export_manifest.json
            echo.whisperbus.archive
            export_pipeline.log

  artifact_check:
    needs: export_pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: export-artifacts
          path: ./downloaded_artifacts

      - name: List downloaded artifact files
        run: ls -l ./downloaded_artifacts

      - name: Verify key files exist
        run: |
          FILES=(
            "echo_full_network.dot"
            "echo_full_network.png"
            "checkpoint_bridge.json"
            "checkpoint_bus.json"
            "export_manifest.json"
            "echo.whisperbus.archive"
            "export_pipeline.log"
          )
          for f in "${FILES[@]}"; do
            if [ ! -f "./downloaded_artifacts/$f" ]; then
              echo "Missing artifact: $f"
              exit 1
            fi
          done
          echo "All key artifacts are present."
