name: Export Echo Network

on: push: branches: [ main ]

jobs: export-network: runs-on: ubuntu-latest

steps:
- name: Checkout repository
  uses: actions/checkout@v3

- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.x'

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install networkx pydot
    sudo apt-get update
    sudo apt-get install -y graphviz

- name: Run export script
  run: |
    chmod +x export_pipeline.sh
    ./export_pipeline.sh

- name: Upload DOT file
  uses: actions/upload-artifact@v3
  with:
    name: echo-dot-network
    path: echo_full_network.dot

- name: Upload PNG file
  uses: actions/upload-artifact@v3
  with:
    name: echo-png-network
    path: echo_full_network.png

