name: Export Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install networkx pydot

    - name: Run export pipeline script
      run: |
        chmod +x export_pipeline.sh
        ./export_pipeline.sh

    - name: Upload all relevant artifacts
      uses: actions/upload-artifact@v4
      with:
        name: limen-echo-core-exports
        path: |
          echo_full_network.dot
          echo_full_network.png
          checkpoint_bridge.json
          checkpoint_bus.json
          export_manifest.json
          echo.whisperbus.archive
          export_pipeline.log
          create_dot_export.py
